variables:
  GIT_STRATEGY: fetch
  DOCKER_DRIVER: overlay

services:
  - docker:dind

backup:
  retry: 2
  script:
    - mkdir backup
    # CloudFlare auth key is here: https://dash.cloudflare.com/profile -> Global API Key -> View
    - docker run -it --rm -e CF_API_KEY="$CF_API_KEY" -e CF_API_EMAIL="$CF_API_EMAIL" lfaoro/flares $CF_DOMAINS_TO_BACKUP > backup/backup.bind
  artifacts:
    untracked: true
    expire_in: 4 week
    name: "backup-${CI_COMMIT_REF_NAME}"
    paths:
     - backup/
